INSERT INTO projects (title, funding_goal) VALUES ("Eden", 100000);
INSERT INTO projects (title, funding_goal) VALUES ("Arcadia", 50000);
INSERT INTO projects (title, funding_goal) VALUES ("Optimus Prime", 300002200);
INSERT INTO projects (title, funding_goal) VALUES ("Archeology", 513248);
INSERT INTO projects (title, funding_goal) VALUES ("Starkiller", 69000);
INSERT INTO projects (title, funding_goal) VALUES ("Last Jedi Rewrite", 54700);
INSERT INTO projects (title, funding_goal) VALUES ("GOT S8 Rewrite", 8904561);
INSERT INTO projects (title, funding_goal) VALUES ("SpaceX", 89513215);
INSERT INTO projects (title, funding_goal) VALUES ("Moon Base", 59412389);
INSERT INTO projects (title, funding_goal) VALUES ("Space Force", 1000000000);

INSERT INTO users (name) VALUES ("Marcus");
INSERT INTO users (name) VALUES ("Sven");
INSERT INTO users (name) VALUES ("Peter");
INSERT INTO users (name) VALUES ("Piotr");
INSERT INTO users (name) VALUES ("Ishmael");
INSERT INTO users (name) VALUES ("Raul");
INSERT INTO users (name) VALUES ("Ignacius");
INSERT INTO users (name) VALUES ("Christopher");
INSERT INTO users (name) VALUES ("Rodrigo");
INSERT INTO users (name) VALUES ("Colby");
INSERT INTO users (name) VALUES ("Fabio");
INSERT INTO users (name) VALUES ("Arcturus");
INSERT INTO users (name) VALUES ("Hercules");
INSERT INTO users (name) VALUES ("Electra");
INSERT INTO users (name) VALUES ("Orpheus");
INSERT INTO users (name) VALUES ("Morpheus");
INSERT INTO users (name) VALUES ("Ricardo");
INSERT INTO users (name) VALUES ("Steven");
INSERT INTO users (name) VALUES ("Plato");
INSERT INTO users (name) VALUES ("Agamemnon");

INSERT INTO pledges (user_id, project_id) VALUES (2,4);
INSERT INTO pledges (user_id, project_id) VALUES (2,3);
INSERT INTO pledges (user_id, project_id) VALUES (4,5);
INSERT INTO pledges (user_id, project_id) VALUES (1,4);
INSERT INTO pledges (user_id, project_id) VALUES (5,3);
INSERT INTO pledges (user_id, project_id) VALUES (6,2);
INSERT INTO pledges (user_id, project_id) VALUES (8,9);
INSERT INTO pledges (user_id, project_id) VALUES (6,5);
INSERT INTO pledges (user_id, project_id) VALUES (2,6);
INSERT INTO pledges (user_id, project_id) VALUES (9,8);
INSERT INTO pledges (user_id, project_id) VALUES (5,6);
INSERT INTO pledges (user_id, project_id) VALUES (6,9);
INSERT INTO pledges (user_id, project_id) VALUES (6,3);
INSERT INTO pledges (user_id, project_id) VALUES (5,4);
INSERT INTO pledges (user_id, project_id) VALUES (8,1);
INSERT INTO pledges (user_id, project_id) VALUES (6,1);
INSERT INTO pledges (user_id, project_id) VALUES (4,3);
INSERT INTO pledges (user_id, project_id) VALUES (1,6);
INSERT INTO pledges (user_id, project_id) VALUES (2,3);
INSERT INTO pledges (user_id, project_id) VALUES (1,3);
INSERT INTO pledges (user_id, project_id) VALUES (3,1);
INSERT INTO pledges (user_id, project_id) VALUES (2,9);
INSERT INTO pledges (user_id, project_id) VALUES (2,7);
INSERT INTO pledges (user_id, project_id) VALUES (7,1);
INSERT INTO pledges (user_id, project_id) VALUES (7,2);
INSERT INTO pledges (user_id, project_id) VALUES (7,3);
INSERT INTO pledges (user_id, project_id) VALUES (7,4);
INSERT INTO pledges (user_id, project_id) VALUES (4,7);
INSERT INTO pledges (user_id, project_id) VALUES (7,5);
INSERT INTO pledges (user_id, project_id) VALUES (7,6);
